# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: OCI-pool

steps:

- script: |
    export OCI_CLI_AUTH=instance_principal
    oci os ns get
  displayName: 'cli testing'

# This piece expects Docker and Fn project SDK installed on the build VM
- script: |
    cd azure-oci/hello-node
    fn -v deploy --app hello-node -no-bump
    echo -n '{"name":"Mika"}' | fn invoke hello-node hello-node
  displayName: 'build and deploy Hello World function with NodeJS'
